# Site settings
title: Eat. Sleep. Android. Linux
email: soham4jam@gmail.com
url: https://sohamj.github.io
description: "Soham Jambhekar"
skills: "Android Developer - Linux Enthusiast - Guitarist"
meta_author: Jambhekar Soham

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: google-plus
    url: https://plus.google.com/u/0/+SohamJambhekar/about
  - title: facebook
    url: https://www.facebook.com/sohamjambhekar
  - title: spotify
    url: https://open.spotify.com/user/soham4jam
  - title: linkedin
    url: https://www.linkedin.com/in/sohamjambhekar
  - title: github
    url: http://github.com/SohamJ

# Postal address (add as many lines as necessary)
address:
  - line: 224 Hamilton Street
  - line: New Brunswick, NJ 08901
  - line: USA

# Credits content
credits: <a href="https://github.com/jeromelachaud/freelancer-theme/tree/master">Freelance theme</a> by jeromelachoud'

# Build settings
markdown: kramdown
permalink: pretty
